### PR TITLE
Don't delete message when PR is merged

### LINKED ISSUE #15: Don't delete messages when PR is merged
I'd rather the bot didn't delete it's messages from the slack channel when the PR is merged. It makes us all sound crazy, and we don't get the history of what PRs have been made. As long as it adds a merged reaction, I think that's sufficient.

### PR DESCRIPTION
**Pull request by dkniffin**
Fixes #15

### CODE REVIEW

**Comment by dacur** [comment]
:+1: very nice

**Comment by sweetmandm** [comment]
The 'merged' icon is an excellent idea. This looks like it leaves `deleteCRMessages` unused, should it be completely removed or is it likely to become necessary again?

**Comment by dkniffin** [comment]
*shrug* @joeyjoejoejr @keeganbrown :point_up: any thoughts on that?

**Comment by keeganbrown** [comment]
So the original idea behind deleting the messages was that the channel could be a running list of PRs that need attention -- if there are no links, then nothing needs doing. If there are links, then there's something that needs to be done. It sounds like people are finding it more useful to have the messages persist for discussion's sake. If that's the case, then yeah this antiquates `deleteCRMessages ` entirely. Although, personally, I'd like to have a stronger visual indicator of a PR that isn't in need of CR than just the merge icon.

**Comment by sweetmandm** [comment]
I don't suppose you can update a message after it's posted? Or edit it? If so, we could change the color of the attachment on #17 for merged branches -- the color is used for that vertical bar that runs across the left side

**Comment by keeganbrown** [comment]
Yes I believe we can edit/update messages after they're posted. Changing the color sounds good to me.

**Comment by dkniffin** [comment]
Maybe change the color *and* add the icon. I know the icon was the old way of indicating it didn't need any more review.

**Comment by joeyjoejoejr** [comment]
Yeah.  I think we should do both.

**Comment by keeganbrown** [comment]
Both sounds good.

**Comment by dkniffin** [comment]
Looks good to me :+1:

**Pull request merged**
